"""
sim_world_voronoi.py — Architecture B: Native Voronoi Cell Geopolitics for REGNUM.

Transforms irregular Voronoi polygons generated by Mapgen2 into the game's
economic, geopolitical, and demographic regions:
- Each land/coastal Voronoi Center becomes a discrete Region.
- True graph-based adjacency: neighbors derived from shared Voronoi edges (no rigid 6-way hex grid).
- Topography-conforming geopolitics: rivers, sheer cliffs, and mountain ridges naturally
  bound provinces and trade corridors.
- 100% conserved currency, banking, government, and trade compatibility.
"""

from __future__ import annotations

import os
import json
import math
import random
from collections import deque
from typing import Dict, List, Optional, Set, Tuple

import numpy as np

from goods import Goods
from region import Region
from nation import Nation
from province import Province, partition_contiguous_graph
import forex as fx
from world_trade import trader_wealth
from terrain_edges import reset_edge_manager
from tile_resources import assign_tile_resources
from world_names import get_starting_nations_claimed_by, assign_world_identities
from polygon_map import PolygonMapGenerator, BIOME_COLORS
from world_config import (
    VORONOI_POINTS,
    VORONOI_ISLAND_SHAPE,
    VORONOI_WIDTH,
    VORONOI_HEIGHT,
)


def _starting_population_for_voronoi_center(center) -> int:
    """Starting population scaled by geography and carrying capacity."""
    if center.ocean:
        return 0
    elev = getattr(center, 'elevation', 0.20)
    biome = getattr(center, 'biome', 'PLAINS').upper()
    is_mountain = (elev >= 0.70) or (biome in ('SNOW', 'TUNDRA', 'BARE', 'SCORCHED'))
    is_coast = center.coast or (biome == 'BEACH')

    if is_mountain:
        return 45
    elif is_coast:
        return 135
    elif elev >= 0.40:
        return 75
    else:
        return 95


def _professions_for_voronoi_center(center) -> dict:
    """Terrain-aware profession distribution."""
    elev = getattr(center, 'elevation', 0.20)
    biome = getattr(center, 'biome', 'PLAINS').upper()
    is_mountain = (elev >= 0.70) or (biome in ('SNOW', 'TUNDRA', 'BARE', 'SCORCHED'))
    is_coast = center.coast or (biome == 'BEACH')

    if is_mountain:
        return {Goods.food: 1.0, Goods.wood: 0.0, Goods.furniture: 0.0}
    elif is_coast:
        return {Goods.food: 0.85, Goods.wood: 0.10, Goods.furniture: 0.05}
    else:
        return {Goods.food: 0.60, Goods.wood: 0.25, Goods.furniture: 0.15}


def build_world_voronoi(
    seed: Optional[int] = None,
    terrain_seed: Optional[int] = None,
    nation_seed: Optional[int] = None,
    num_points: Optional[int] = None,
    island_shape: Optional[str] = None,
    existing_gen: Optional[PolygonMapGenerator] = None,
    num_nations: int = 3,
):
    """Generate a native Voronoi cell world for REGNUM using Mapgen2.

    Returns:
        (tiles, nations, gen)
    """
    # Check saved_slots/slot_1.json for default persistent world configuration
    slot_1_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "saved_slots", "slot_1.json")
    slot_state = {}
    if (seed is None and terrain_seed is None) and os.path.exists(slot_1_file):
        try:
            with open(slot_1_file, "r", encoding="utf-8") as f:
                slot_data = json.load(f)
                slot_state = slot_data.get("state", {})
                if "seed" in slot_state:
                    seed = int(slot_state["seed"])
                    terrain_seed = seed
                if "shape" in slot_state and island_shape is None:
                    island_shape = slot_state["shape"]
                if "points" in slot_state and num_points is None:
                    num_points = int(slot_state["points"])
        except Exception as exc:
            pass

    if terrain_seed is None:
        terrain_seed = seed if seed is not None else random.randint(1, 999999)
    if nation_seed is None:
        if "nation_seed" in slot_state:
            nation_seed = int(slot_state["nation_seed"])
        else:
            nation_seed = random.randint(1, 999999)

    rng_nation = random.Random(nation_seed)

    # 1. Generate or reuse Mapgen2 Voronoi Graph
    pts_count = num_points if num_points is not None else VORONOI_POINTS
    shape_val = island_shape if island_shape is not None else VORONOI_ISLAND_SHAPE

    if existing_gen is not None:
        gen = existing_gen
    else:
        gen = PolygonMapGenerator(
            seed=terrain_seed,
            width=int(VORONOI_WIDTH),
            height=int(VORONOI_HEIGHT),
            num_points=pts_count,
            island_shape=shape_val,
            river_count=22,
            mountain_sharpness=1.0,
            enable_corner_improvement=True,
            enable_roads=True,
            enable_lava=False,
            enable_noisy_edges=True,
        )

    tiles: List[Region] = []
    by_name: Dict[str, Region] = {}
    layout: Dict[str, Tuple[float, float]] = {}

    # 2. Convert Voronoi Centers into Region tiles
    for c in gen.centers:
        name = f"c{c.index}"
        tile = Region(name, t=0, wilderness=True)

        tile.center = c
        tile.centroid = (float(c.x), float(c.y))
        tile.corners = c.corners
        tile.borders = c.borders
        tile.polygon = gen.get_polygon_noisy_boundary(c)

        tile.is_ocean = bool(c.ocean)
        tile.is_coast = bool(c.coast)
        tile.is_river_corridor = any(e.river > 0 for e in c.borders)
        tile.elevation = float(c.elevation)
        tile.elevation_meters = int(c.elevation * 3000)
        tile.biome = str(c.biome).lower()
        tile.terrain_color = BIOME_COLORS.get(c.biome, (120, 160, 100))

        if tile.is_ocean:
            tile.elevation = -0.30
            tile.elevation_meters = -450
            tile.wilderness_pop = 0
            tile.agents = []
        else:
            tile.wilderness_pop = int(_starting_population_for_voronoi_center(c) * 0.8)

        tile.adjacent_tiles = {}
        c.region = tile
        tiles.append(tile)
        by_name[name] = tile
        layout[name] = (float(c.x), float(c.y))

    # Link adjacent Voronoi tile neighbors
    for c in gen.centers:
        tile = by_name[f"c{c.index}"]
        for n in c.neighbors:
            nbr_tile = by_name[f"c{n.index}"]
            tile.adjacent_tiles[nbr_tile.name] = nbr_tile

    # 3. Starting Global Powers claim contiguous Voronoi clusters strictly on land
    if num_nations == 3:
        claimed_by = get_starting_nations_claimed_by(seed=nation_seed)
    else:
        all_powers = [
            ("United States", "USD", 3),
            ("China", "CNY", 4),
            ("Japan", "JPY", 5),
            ("India", "INR", 4),
            ("Indonesia", "IDR", 3),
            ("Brazil", "BRL", 4),
            ("Mexico", "MXN", 3),
            ("Nigeria", "NGN", 4),
        ]
        claimed_by = {}
        for cname, cur, n_t in all_powers[:max(1, min(len(all_powers), num_nations))]:
            claimed_by[cname] = (cur, n_t)
    nations: List[Nation] = []

    def _unclaimed_land_tiles() -> List[Region]:
        return [t for t in tiles if not t.is_ocean and getattr(t, 'owner_nation', None) is None]

    for nname, (cur, n_tiles) in claimed_by.items():
        regime = "democracy" if rng_nation.random() > 0.5 else "autocracy"
        n = Nation(nname, currency=cur, regime_type=regime, initial_cash=1000.0)
        nations.append(n)

        open_tiles = _unclaimed_land_tiles()
        if not open_tiles:
            break

        # Pick seed: prefer fertile lowlands/coasts with central distance
        open_tiles.sort(key=lambda t: (
            t.elevation >= 0.70,  # avoid high mountains as capital
            abs(t.centroid[0] - VORONOI_WIDTH / 2.0) + abs(t.centroid[1] - VORONOI_HEIGHT / 2.0)
        ))
        # Choose among top candidates with randomness
        cand_pool = open_tiles[:max(1, len(open_tiles) // 3)]
        seed_tile = rng_nation.choice(cand_pool)

        # Graph BFS cluster growth over land neighbors
        cluster_names: List[str] = [seed_tile.name]
        frontier_names: List[str] = [seed_tile.name]
        seen: Set[str] = {seed_tile.name}

        while len(cluster_names) < n_tiles:
            grown = False
            rng_nation.shuffle(frontier_names)
            for curr_name in list(frontier_names):
                curr = by_name[curr_name]
                nbrs = [by_name[n_name] for n_name in curr.adjacent_tiles.keys()]
                valid_nbrs = [nbr for nbr in nbrs
                              if not nbr.is_ocean and nbr.name not in seen and getattr(nbr, 'owner_nation', None) is None]
                # Prioritize river corridors and lowland basins for natural territorial growth
                valid_nbrs.sort(key=lambda x: (not x.is_river_corridor, x.elevation))
                for nbr in valid_nbrs:
                    seen.add(nbr.name)
                    cluster_names.append(nbr.name)
                    frontier_names.append(nbr.name)
                    grown = True
                    if len(cluster_names) >= n_tiles:
                        break
                if len(cluster_names) >= n_tiles:
                    break
            if not grown:
                remaining_open = [t for t in _unclaimed_land_tiles() if t.name not in seen]
                if not remaining_open:
                    break
                extra = remaining_open[0]
                seen.add(extra.name)
                cluster_names.append(extra.name)
                frontier_names.append(extra.name)

        # 4. Balanced Provinces: split cluster into 1-2 balanced contiguous sub-provinces
        cluster_tiles = [by_name[cname] for cname in cluster_names]
        cluster_set = set(cluster_names)
        n_parts = 1 if len(cluster_tiles) < 4 else 2
        parts = partition_contiguous_graph(
            cluster_tiles,
            neighbors_func=lambda t: [by_name[nbr_name] for nbr_name in t.adjacent_tiles.keys() if nbr_name in cluster_set],
            nparts=n_parts,
            rng=rng_nation,
            pos_func=lambda t: t.centroid
        )

        for part in parts:
            prov = Province(f"{nname}-{len(n.provinces)+1}", n, t=0)
            for i, old_tile in enumerate(part):
                idx = tiles.index(by_name[old_tile.name])
                init_pop = _starting_population_for_voronoi_center(old_tile.center)
                init_profs = _professions_for_voronoi_center(old_tile.center)
                claimed = Region(
                    old_tile.name,
                    t=0,
                    number_of_agents=init_pop,
                    profession_distribution=init_profs,
                    number_of_traders=2,
                    institutions=prov.institutions,
                    seat_gov=(i == 0)
                )

                # Preserve all Voronoi geometric and geographic attributes
                claimed.center = old_tile.center
                claimed.centroid = old_tile.centroid
                claimed.corners = old_tile.corners
                claimed.borders = old_tile.borders
                claimed.polygon = old_tile.polygon
                claimed.adjacent_tiles = old_tile.adjacent_tiles

                claimed.elevation = old_tile.elevation
                claimed.elevation_meters = old_tile.elevation_meters
                claimed.biome = old_tile.biome
                claimed.terrain_color = old_tile.terrain_color
                claimed.is_ocean = old_tile.is_ocean
                claimed.is_coast = old_tile.is_coast
                claimed.is_river_corridor = old_tile.is_river_corridor

                tiles[idx] = claimed
                by_name[claimed.name] = claimed
                old_tile.center.region = claimed
                old_tile.owner_nation = n
                prov.add_tile(claimed)
                n.add_tile(claimed)
            n.provinces.append(prov)

        # Update adjacent_tiles references immediately after claiming nation
        for t in tiles:
            for n_name in list(t.adjacent_tiles.keys()):
                t.adjacent_tiles[n_name] = by_name[n_name]

    # Update adjacent_tiles references to point to any newly claimed Region instances
    for t in tiles:
        for n_name in list(t.adjacent_tiles.keys()):
            t.adjacent_tiles[n_name] = by_name[n_name]

    # 5. Geographic Passability & Trade Network Degree Capping
    edge_mgr = reset_edge_manager(tiles, layout)

    # Guarantee mountain peaks have at least 1-2 passable passes
    for tile in tiles:
        if tile.is_ocean:
            continue
        if tile.elevation >= 0.70:
            candidates = []
            passable_count = 0
            for other in tile.adjacent_tiles.values():
                if not other.is_ocean:
                    edge = edge_mgr.get_edge(tile.name, other.name)
                    if edge and edge.passable:
                        passable_count += 1
                    if edge:
                        candidates.append((edge.elevation_delta, other.name))
            if passable_count == 0 and candidates:
                candidates.sort(key=lambda x: x[0])
                for _, other_name in candidates[:min(2, len(candidates))]:
                    edge_mgr.unblock_mountain_pass(tile.name, other_name)

    def _max_trade_partners(t: Region) -> int:
        return 2 if t.elevation >= 0.70 else 3

    # Gather candidate passable land-to-land edges
    candidate_edges = []
    seen_cand = set()
    for tile in tiles:
        if tile.is_ocean:
            continue
        for other in tile.adjacent_tiles.values():
            if other.is_ocean:
                continue
            edge_key = tuple(sorted((tile.name, other.name)))
            if edge_key in seen_cand:
                continue
            if edge_mgr.is_passable(tile.name, other.name):
                seen_cand.add(edge_key)
                edge = edge_mgr.get_edge(tile.name, other.name)
                score = 100.0
                if edge and edge.is_river:
                    score += 160.0
                if edge and edge.has_mountain_pass:
                    score += 80.0
                t_nation = getattr(tile, 'owner_nation', None)
                o_nation = getattr(other, 'owner_nation', None)
                if t_nation is not None and t_nation == o_nation:
                    score += 40.0
                frict = edge.friction if edge else 1.0
                dh = abs(tile.elevation - other.elevation)
                score -= frict * 15.0 + dh * 30.0
                candidate_edges.append((score, tile, other))

    candidate_edges.sort(key=lambda x: x[0], reverse=True)

    # Pass 1: Ensure every land tile gets at least 1 connection
    tile_cand_map: Dict[str, list] = {}
    for score, t_a, t_b in candidate_edges:
        tile_cand_map.setdefault(t_a.name, []).append((score, t_b))
        tile_cand_map.setdefault(t_b.name, []).append((score, t_a))

    for t in tiles:
        if t.is_ocean:
            continue
        if len(t.neighbors) == 0 and t.name in tile_cand_map:
            for _, cand in tile_cand_map[t.name]:
                if len(cand.neighbors) < _max_trade_partners(cand):
                    t.add_neighbor(cand)
                    cand.add_neighbor(t)
                    break
            if len(t.neighbors) == 0 and tile_cand_map[t.name]:
                sorted_cands = sorted(tile_cand_map[t.name], key=lambda sc: len(sc[1].neighbors))
                best_cand = sorted_cands[0][1]
                t.add_neighbor(best_cand)
                best_cand.add_neighbor(t)

    # Pass 2: Greedily connect high-value corridors up to degree caps
    for _, t_a, t_b in candidate_edges:
        cap_a = _max_trade_partners(t_a)
        cap_b = _max_trade_partners(t_b)
        if len(t_a.neighbors) < cap_a and len(t_b.neighbors) < cap_b:
            if t_b.name not in t_a.neighbors:
                t_a.add_neighbor(t_b)
                t_b.add_neighbor(t_a)

    # Pass 3: Strict degree cap guarantee
    for t in tiles:
        if t.is_ocean:
            continue
        max_cap = _max_trade_partners(t)
        while len(t.neighbors) > max_cap:
            removable = [n for n in t.neighbors.values() if len(n.neighbors) > 1]
            if not removable:
                removable = list(t.neighbors.values())
            victim = max(removable, key=lambda n: abs(t.elevation - n.elevation) + edge_mgr.get_friction(t.name, n.name))
            t.neighbors.pop(victim.name, None)
            t.routes.pop(victim.name, None)
            victim.neighbors.pop(t.name, None)
            victim.routes.pop(t.name, None)

    # Pass 4: Global Connectivity Bridging (100% of land tiles connected)
    land_tiles = [t for t in tiles if not t.is_ocean]

    def _get_trade_components():
        visited = set()
        comps = []
        for lt in land_tiles:
            if lt.name not in visited:
                comp = []
                queue = [lt]
                visited.add(lt.name)
                while queue:
                    curr = queue.pop(0)
                    comp.append(curr)
                    for n in curr.neighbors.values():
                        if n.name not in visited and not n.is_ocean:
                            visited.add(n.name)
                            queue.append(n)
                comps.append(comp)
        return comps

    trade_comps = _get_trade_components()
    while len(trade_comps) > 1:
        trade_comps.sort(key=len, reverse=True)
        main_comp = trade_comps[0]
        main_names = {t.name for t in main_comp}

        best_bridge = None
        best_bridge_score = -1e9
        for other_comp in trade_comps[1:]:
            for t_other in other_comp:
                for t_main in t_other.adjacent_tiles.values():
                    if t_main.name in main_names and not t_main.is_ocean:
                        dh = abs(t_other.elevation - t_main.elevation)
                        score = -dh * 20.0
                        if score > best_bridge_score:
                            best_bridge_score = score
                            best_bridge = (t_other, t_main)

        if best_bridge:
            u, v = best_bridge
            edge_mgr.unblock_mountain_pass(u.name, v.name)
            u.add_neighbor(v)
            v.add_neighbor(u)
            trade_comps = _get_trade_components()
        else:
            break

    # 6. Forex Desks between adjacent claimed tiles
    seen_desks = set()
    for a in tiles:
        if getattr(a, 'owner_nation', None) is None:
            continue
        for other in a.neighbors.values():
            if getattr(other, 'owner_nation', None) is None:
                continue
            key = tuple(sorted((a.name, other.name)))
            if key in seen_desks:
                continue
            seen_desks.add(key)
            fx.connect_desks(a, other, t=0)

    for r in tiles:
        if getattr(r, 'owner_nation', None) is not None:
            r._init_trader_wealth = trader_wealth(r)
        else:
            r._init_trader_wealth = 0.0

    # 7. Procedural Natural Resources & City/Country Names
    assign_tile_resources(tiles, seed=seed if seed is not None else 42)
    assign_world_identities(tiles, nations, seed=nation_seed)

    return tiles, nations, gen
